In [23]:
word = 'I love Python programming'
print(word[-18:-12])
num = 2
yo


Python


In [143]:
foo = [1,2,3]
bar = foo.copy()
print(foo * 2)

[1, 2, 3, 1, 2, 3]


In [46]:
2*word

'I love Python programmingI love Python programming'

In [55]:
# Map function applies a function to an iterable and returns a map object.

number_list = [1,2,3,4,5]
squared_list = list(map(lambda x : x**2,number_list))
print(squared_list) #-> [1, 4, 9, 16, 25]
# Map appiles the lambda function to each element in the input list
# Map -> [f(1),f(2),f(3),f(4),f(5)]

# Reduce function applies a funtion to an iterable and reduces it to a single cumulative value.

from functools import reduce

sum_of_squared_list = reduce(lambda x , y : x + y , squared_list)
print(sum_of_squared_list) #-> 55
# Reduce nests the lambda function
# Reduce -> f(f(f(f(1,2) ,f(3)),f(4)),f(5))





[1, 4, 9, 16, 25]
55


In [60]:
a = (1,2,3,4)
print(id(a))
b = [4,5]
a = a[:3]
print(id(a))


140430245517968
140430245573632


In [79]:
info = {"Name":"Akhil", "Age": 27,"List": ["yo","bitch"]}
dup = info
print(id(info),id(dup))
info["Name"] = "Akshay"
print(dup.get("Name"))

140430245505408 140430245505408
Akshay


In [82]:
for key, value in info.items():
    print(key, value)

Name Akshay
Age 27
List ['yo', 'bitch']


In [76]:
info['Age'] = info["Age"] + 3

In [78]:
ls = [2,3,4,"Hello","Akhil","Akhil"]
s = set(ls)
print(s)

{2, 3, 4, 'Hello', 'Akhil'}


In [86]:
d = {0: 'Fish', 1: 'Bird', 2: 'Mammal'}
for i in d:
    print(i)

0
1
2


In [87]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))

None
None
None


In [103]:
para = ["Yo hows it going", "My name is steve", "I am gay"]

# for sentence in para:
#     for word in sentence.split()

word_list = [word for sentence in para for word in sentence.split()]
print(word_list)

['Yo', 'hows', 'it', 'going', 'My', 'name', 'is', 'steve', 'I', 'am', 'gay']


In [104]:
vowel_list = ['a','e','i','o','u']

# for sentence in para:
#     for word in sentence.split():
#         if word[0] in vowel_list:

vowel_word_list = [word for sentence in para for word in sentence.split() if word[0].lower() in vowel_list]
print(vowel_word_list)


['it', 'is', 'I', 'am']


In [127]:
a = {1,2,4,5}
print(*a)
print(1,2,4,5)

1 2 4 5
1 2 4 5


In [135]:
a = {"One":1,"two":2}
print(*a)

One two


In [128]:
def suml(*a):
    print("Hai",a)
    print("Hai",*a)

suml("hello","yo",3,[1,2,4])

Hai ('hello', 'yo', 3, [1, 2, 4])
Hai hello yo 3 [1, 2, 4]


In [141]:
num = [1,2,3,4,5,6,7,8,9,10]

l1 = list(map(lambda x : x%2 == 0,num))
print(l1)
# Filter needs True/False list and filters the input list
l2 = list(filter(lambda x : x%2 == 0,num))
print(l2)

[False, True, False, True, False, True, False, True, False, True]
[2, 4, 6, 8, 10]


In [142]:
max = reduce(lambda x, y : x if x > y else y,num)
print(max)

10


In [150]:
# Read the input as an integer
n = int(input())
print(n)

# Import the reduce() function
from functools import reduce

# Write your code here
if n == 0 : 
    fact = 1
else:
    fact = reduce(lambda x,y : x*y, list(range(1,n+1)))
    
print(fact)

4
24


In [147]:
# learn more 
# sets and set theory using set datastructure.
# args and kwargs
# map,reduce,filter
# list and dictionary comprehensions

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
import numpy as np

arr = np.array(range(5))
print(dir(arr))


(5,)

In [13]:
arr = np.array([1,2,True,"True"])
print(arr)
print(type(arr))
#arr = np.array([1,2,True])
#print(arr *2)

['1' '2' 'True' 'True']
<class 'numpy.ndarray'>


In [30]:
arr = np.array(range(10))
#arr[(arr > 4) and (arr < 9)]
arr[(arr > 4) & (arr < 9)]

# Difference between 'and' and '&'

array([5, 6, 7, 8])

In [40]:
arr = np.array([[1,2],[2,3],[3,4]])
arr * np.array([3,2.2])
# Element wise multiplication with '*'


array([[3. , 4.4],
       [6. , 6.6],
       [9. , 8.8]])

In [53]:
ones = np.ones((2,2,2,2))
print(ones)
print(ones.shape)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]
(2, 2, 2, 2)


In [17]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr,"\n\n")
print(arr.reshape(-1,2)) # "-1" in reshape implies that it is unspecified
arr = np.array([[1,2,5],[3,4,6],[3,4,5]])
print(arr,"\n\n\n")
print(arr.reshape(-1)) # just a single '-1' will unravel the array
print(arr.reshape(1,-1)) # The dimension of the array is specified by the number of elements you specify in the tuple. Here, the answer is 2-D array.

[[1 2]
 [3 4]] 


[[1 2]
 [3 4]]
[[1 2 5]
 [3 4 6]
 [3 4 5]] 



[[1 2 5 3 4 6 3 4 5]]


In [18]:
string = "abcdefg"

print("string :",string)

print("string[-5:] :",string[-5:])

print("string[-1:-5] :",string[-1:-5])

print("string[-5:-1] :",string[-5:-1])

print("string[-5:-7] :",string[-5:-7])

#In all the above cases the step size is by default '1'.

#So the string will always be read left to right.

#Therefore the second parameter in the index should be greater than the first one.

#else will return nothing

 

print("string[-1:-6:-1] :",string[-1:-6:-1])

print("string[-6:-1:-1] :",string[-6:-1:-1])

#In the above example the step size was changed to '-1'.Hence the string is read right to left.

#Here the first parameter in the index should be greater than the second.

#else will return nothing

string : abcdefg
string[-5:] : cdefg
string[-1:-5] : 
string[-5:-1] : cdef
string[-5:-7] : 
string[-1:-6:-1] : gfedc
string[-6:-1:-1] : 


In [ ]:
# Look into this
# DataFrames
# Aggregation and GroupBy
# Split->Apply->Combine

In [2]:
# Iterators and Generators

x = range(10)
print(type(x))
print(dir(x))

import sys 

print(sys.getsizeof(x))
print(sys.getsizeof([x for x in range(10)]))

# Map function is an iterator
# for loop calls next() on the iterable.

<class 'range'>
['__bool__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index', 'start', 'step', 'stop']


In [8]:
import inspect
import pandas as pd

print(inspect.getsource(pd))

# flake8: noqa

__docformat__ = "restructuredtext"

# Let users know if they're missing any of our hard dependencies
hard_dependencies = ("numpy", "pytz", "dateutil")
missing_dependencies = []

for dependency in hard_dependencies:
    try:
        __import__(dependency)
    except ImportError as e:
        missing_dependencies.append(f"{dependency}: {e}")

if missing_dependencies:
    raise ImportError(
        "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
    )
del hard_dependencies, dependency, missing_dependencies

# numpy compat
from pandas.compat import (
    np_version_under1p18 as _np_version_under1p18,
    is_numpy_dev as _is_numpy_dev,
)

try:
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
except ImportError as e:  # pragma: no cover
    # hack but overkill to use re
    module = str(e).replace("cannot import name ", "")
    raise ImportError(
        f"C extension: {module} not built. If you want to import "


In [16]:
string = "Python"
string2 = "go"
print(type(string))
print(dir(string))

<class 'str'>
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [18]:
print(string.__add__(string2))
print(string + string2)

Pythongo
Pythongo


In [ ]:
# movies.isnull().any().value_counts()
# movies is a dataframe
# .all() vs .any()
# How to check for nulls in dataframe.Check how many columns with nulls.